# @package _global_

# use 
# mpy main.py +hsearch=CNN3D model=CNN3D data.task_name=AB

defaults:
  - override /hydra/sweeper: optuna

# choose metric which will be optimized by Optuna
tune_metric: "valid/epoch/AUROC"

# provide a model
module:
  model: ???

hydra:
  # here we define Optuna hyperparameter search
  # it optimizes for value returned from function with @hydra.main decorator
  # learn more here: https://hydra.cc/docs/next/plugins/optuna_sweeper
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    storage: null
    study_name: null
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: maximize

    # number of experiments that will be executed
    n_trials: 150

    # choose Optuna hyperparameter sampler
    # learn more here: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 99
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 10
      n_ei_candidates: 24
      multivariate: false
      warn_independent_sampling: true

    # define range of hyperparameters
    search_space:
      module/optim: 
        type: categorical
        choices: [Adam, SGD]
      module.optim.lr:
        type: float
        low: 1E-6
        high: 0.008
        log: true
      module.optim.weight_decay:
        type: float
        low: 1E-6
        high: 1E-2
        log: true
      module.model.dropout:
        type: float
        low: 0.3
        high: 0.7
      module.model.use_same_lstm:
        type: categorical
        choices: [True, False]
