_target_: src.module.model.TwoHeadLSTM.TwoHeadLSTM

arch: TwoHeadLSTM
num_emb: ${data.num_distinct_gestures}
emb_dim: 128
hidden_dim: 1024
num_layers: 2
dropout: 0.3
linear_dim: 1024
use_same_lstm: True